---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mdegouw-nl
  namespace: networking
spec:
  secretName: mdegouw-nl-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ${SECRET_DOMAIN}
  dnsNames:
    - ${SECRET_DOMAIN}
    - "*.${SECRET_DOMAIN}"
