apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:G7Rb9innKwpvh17oj+G44U6cwkI32KfTu0mqwHDqEnASOKB6taWz/1K6oDtIyj2TxXEV3Zy2ugZhS5HG,iv:wdlshQYR+wjEE5Ighn5PnGUOGQn9DPBDwl8FKC0M+9Y=,tag:Mr9Xn9fmrSjEUSPRfeob6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gd6r3clc7ancjq4g04mag4chl0wudf7qh7hevwy9qxl9tvchdygshazl6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ0lncEhydDd4SzFZRXht
            WDJCb2JZTFFhZGhmcEYwNndHdDh4RDVqa21jCjZBQ0lsbzBqaEQzSjZtYitqQXhQ
            RjlRNGZDallFNHpYenZwdERkRnN5bG8KLS0tIENPOERPRHRpMWhEWkZubDVCS0NI
            Y1l3c3JrQTgwSmFIMTJUMk9Vb2F6bUkKeFl02+ydXXjbqN7uLFgHH4FPeN1LB/Yo
            Qc6upEeYLC0VzDRAiERFjqapJlCRs1aQr5X7COORr3nHLrIQxgHRZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T20:36:03Z"
    mac: ENC[AES256_GCM,data:M0h/febFf6yPbcs82nQMjN/QBP6k9taI6TTcEZirhtBnFfa0US1xfI0zW8yNqVCEIwQrNpn7ePuZJ7pmF/ZUbEKY+QJ5ewrt4WLuV2lD1sB2i9+oq1SHhWYEB8M+j/PxCgXFuiwgM7PHh5ADKES6P1XYnvA2BK8VWEymaEYtT38=,iv:tgU3R7nvU8wL1gdHb8aBD2UclHj+lE3arwtVU5nPv84=,tag:2PNI5t2GOsu4uH1esQWyeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
