---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Amsterdam"
  KUBE_VIP_ADDR: "192.168.178.169"
  METALLB_LB_RANGE: "192.168.178.170-192.168.178.180"
  METALLB_K8S_GATEWAY_ADDR: "192.168.178.170"
  METALLB_INGRESS_ADDR: "192.168.178.171"
